### PR TITLE
Prevent calls to get_child with temporary default values

### LINKED ISSUE #42: Passing temporary object as default value to get_child
Consider following example

```
#include <iostream>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

int main()
{
	using namespace boost::property_tree;
	
	std::stringstream ss;
	ss << "{\"someRandomNode\":false}";

	ptree json;
	read_json(ss, json);

	const auto &node = json.get_child("otherNode", ptree{});
	std::cout << node.size() << " " << (node.begin() == node.end()) << std::endl;

	for (const auto &[k, v] : node)
		std::cout << "Why did i get here?" << std::endl;

	return 0;
}
```

Output:
> 0 0
> Why did i get here?
> Segmentation fault

Obviously get_child returns broken reference leading to undefined behaviour. 
Tested with g++ (Gentoo 8.3.0-r1 p1.1) 8.3.0 and boost 1.70.0.

### PR DESCRIPTION
**Pull request by ashtum**
Resolves #42

### CODE REVIEW

**Comment by ashtum** [comment]
@pdimov, do you have any suggestions on how to add a test to verify that get_child doesn't compile with temporary default values? Can I use a concept and include it as a test for C++20 and higher? (although it doesn't look elegant)

**Comment by pdimov** [comment]
Use a compile-fail test.

**Comment by ashtum** [comment]
> Use a compile-fail test.

Just out of curiosity, is there any alternative way to test it without using a separate compilation unit? I mean, in complex scenarios, the compilation failure could be due to other reasons as well.

**Comment by pdimov** [comment]
There probably is but I wouldn't recommend it.

**Comment by pdimov** [comment]
Something like https://godbolt.org/z/j7MaTGTcd.

**Comment by ashtum** [comment]
> Something like https://godbolt.org/z/j7MaTGTcd.

Do you discourage it because of the possibility of the expression becoming invalid for other reasons and not manifesting itself in the test? If that's the case, can't we mitigate this by also testing valid expressions, like so:

```C++
static_assert(mp_valid<accepts_default_of_type, ptree&>::value, "");
static_assert(mp_valid<accepts_default_of_type, const ptree&>::value, "");
```

**Comment by pdimov** [comment]
It's too complicated, requires specialized knowledge to understand, and is therefore hard to maintain.

**Pull request merged**
