### PR TITLE
 Account for character class being char or unsigned char.

### PR DESCRIPTION
**Pull request by saturnjct**
Avoid comparing to <= 0xFF and triggering a GCC warning. See https://svn.boost.org/trac/boost/ticket/5598

### CODE REVIEW

**Comment by LRFLEW** [comment]
Perhaps you should also add `signed char` to that, since it is considered a separate type from `char`.

**Comment by ashtum** [comment]
@pdimov, it seems that this issue existed in earlier versions of GCC. I was unable to replicate it using any compiler except GCC 4.1.2: https://godbolt.org/z/W4e6e5hdT
Considering that create_escapes is a templated function, I assume that receiving no warning is the expected behavior which has been fixed in later versions of GCC.
Do you think this is still worth fixing?

**Comment by pdimov** [comment]
Link to ticket for reference: http://trac.cpp.al/trac10/ticket/5598

**Comment by pdimov** [comment]
No, I don't think we need to care about GCC 4.1 at this point. The minimum supported version in Boost today is 4.8.

**Pull request closed without merging**
