### PR TITLE
Replace the usage of typeid with boost::typeindex

### PR DESCRIPTION
**Pull request by cdglove**
Allows compilation without rtti

### CODE REVIEW

**Comment by BenBE** [comment]
What's the state of this pull request? I'm running into the same issue too.

Anything left open for this to get merged?

**Comment by huangqinjin** [comment]
+1

**Comment by SiarheiFedartsou** [comment]
Hi! Can I somehow help to have it merged?

**Comment by DmitryAk** [comment]
@madmongo1 hi, could you please look at this?
Thanks in advance!

**Comment by madmongo1** [comment]
Yep, thanks

**Comment by ashtum** [comment]
@pdimov I believe this can be closed as it is already addressed in https://github.com/boostorg/property_tree/commit/3b7c3ccb6bf5438c1a2d1b663762d69760a6386d

**Pull request closed without merging**
